### ISSUE TITLE
Chisel incompatibility

### ISSUE THREAD

**Issue by Basaaa** [MachineMuse/MachineMusePowersuits#563]
When Chisel is installed, the harvest level of alot of blocks is set to 'chisel' instead of 'pickaxe'. smooth stone is a good example. This makes breaking stone impossible with my power fist. This is for eample the cause in DW20 1.7.10. This makes the mod pretty much useless.

**Comment by Korynkai** [comment]
Hmm, seems like this could be related to an old bug that was fixed which involved the inability to break, for instance, stone, basalt and marble. Will thoroughly look into this, but as I recall, the fix for said old issue actually had to be implemented in ProjectRed itself. As such, I wonder if this issue is actually in Powersuits or Chisel...

**Comment by MachineMuse** [comment]
Let me know if this works!
