### ISSUE TITLE
Radial selector for rightclick modules

### ISSUE THREAD

**Issue by MachineMuse** [MachineMuse/MachineMusePowersuits#589]
Current system is OK but is annoying to scroll through large numbers of modules.

**Comment by aionys** [comment]
The only thing I really disliked was that I keep forgetting I have to not be sneaking to be able to switch to another item on the hot bar.

As a suggestion, holding down the quick switch number for the glove (such as 1 if it's in hot bar slot 1) brings up the radial menu, so as not to even further clutter up the keybinds?

**Comment by MachineMuse** [comment]
That's a brilliant idea, thank you. I was trying to think of an elegant solution.

**Comment by aionys** [comment]
:)

**Comment by EzerArch** [comment]
For a moment I read title as "*Radical* selector for rightclick modules", I was like "Yay?".

> so as not to even further clutter up the keybinds?

If I had to keybind every module I actually use, I'd have to use 1/3 of my keyboard only for MPS. Add Galacitcraft, JourneyMap and ShoulderSurfing... look, I need an extra keyboard .

Since we are on this subject: I would move all on/off modules that don't need quick access from keybinding to a separate window, probably on the same Radial selector UI, where I can turn on and off the modules with mouse-click. For the modules I need quick-access (e.g. flight control), I would still use keybinds.

I would organize all modules like this:

* Power Fist modules, i.e. weapons and tools: go to the radial selector. If there are too many, they can be separated into profiles such as "Battle", "Work" etc.

* Other modules: the player can choose either to keybind them or to manage them via HUD interface, turning them on and off with mouse-click. This means the "Keybinds" window should have a way to tell which module will be controlled via HUD instead of a keybind (why not both?).

![2015-08-30_11 56 30](https://cloud.githubusercontent.com/assets/6743303/9570398/cca20860-4f60-11e5-9432-4509d29866a1.png)

**Comment by aionys** [comment]
I like the look of that mock up, but I think the power fist modules and the suit modules should be kept separate, assuming MM wants to do HUD control of suit modules, of course.

If HUD control for suit modules is a thing, I'd say just put all of the installed modules on the HUD by default, maybe with a hide button, and leave the current key binding menu as is.

**Comment by EzerArch** [comment]
> but I think the power fist modules and the suit modules should be kept separate, assuming MM wants to do HUD control of suit modules, of course.

It's because I didn't want to create another window, one for controlling power fist modules and another for suit modules, still having an easy way control modules.

I could suggest making the "Keybinds" window into a module manager where you can turn on and off modules, set keybinds and enable/disable show module icon on HUD. Instead of using hooks to assign the key, each module would be have a bar like this:

![image4417-1](https://cloud.githubusercontent.com/assets/6743303/9570907/c07cfc24-4f6b-11e5-9cf9-ea12f533a99d.png)

>  I'd say just put all of the installed modules on the HUD by default, 

There would be a problem: what if the player install many modules? Would they all fit on screen with other UI elements from other mods? I think letting the player choose which module icon should be put on the HUD would address this issue. He can then drag the icons where they best fit... well this is a discussion for the issue #590. (I'll be moving this part to there)

**Comment by eyeonus** [comment]
What part of the code deals with this? I kind of want to take a look at it.

**Comment by aionys** [comment]
*take

**Comment by lehjr** [comment]
There is no central part of the code that currently deals with this. Everything is broken up into different places. Care must be taken because in certain render loops, as this can cause all kinds of issues.

**Comment by lehjr** [comment]
That said, a big chunk is in net.machinemuse.powersuits.event.ClientTickHandler, but the power fist icon rendering is not. That's actually in Numina, as this project was also using it: https://github.com/MachineMuse/Anima

But it was never fleshed out, so I have no idea what direction it was going in. It did look interesting though.

**Comment by lehjr** [comment]
Powerfist code:
net.machinemuse.numina.render.RenderGameOverlayEventHandler#drawModeChangeIcons()

**Comment by lehjr** [comment]
@aionys I think with the fantastic work you did on the meters, this shouldn't be too bad. I'm not sure if I like the design, but it might grow on me.

**Comment by eyeonus** [comment]
Design of what now?

**Comment by lehjr** [comment]
https://github.com/MachineMuse/MachineMusePowersuits/issues/589#issuecomment-136226542

**Comment by eyeonus** [comment]
Oh, yeah, that's a lot of effort to get going.

I was thinking of starting small, i.e., just the powerfist modules for now. Iterative changes. First step, making the current functionality happen when you hold the hotbar number the fist is in and scroll, rather than sneak. (My suggestion [here](https://github.com/MachineMuse/MachineMusePowersuits/issues/589#issuecomment-136128922).)

**Comment by eyeonus** [comment]
Definitely not going to do all the things in that mockup.

The circle in the middle probably, I don't know about the other stuff, though.

**Comment by lehjr** [comment]
you mean what you were describing here then? https://github.com/MachineMuse/MachineMusePowersuits/issues/589#issuecomment-136128922
yeah, that's probably more realistic. The only thing is that the "sneak" part of that operation isn't handled there.

**Comment by eyeonus** [comment]
Why am I not surprised. LOL. I'll look at it when I get home from work and see what's what, but yes, precisely.

**Comment by lehjr** [comment]
Yeah the code is broken up everywhere, sometimes out of necessity, sometimes I have no idea.

**Comment by eyeonus** [comment]
Obviously some of the coders on this project were a bit more skilled than others.

Like, whoever originally wrote the meter classes didn't even think about inheritance. Like what I did with super.draw in the energy meter to make it so I didn't have to copy the whole draw method just to make it also draw the lightning too.

Duplicating an entire method just because you're using a different texture, which is how the code was originally, is a huge waste and kind of defeats the purpose of having it inherit in the first place.

**Comment by lehjr** [comment]
Some of the oddities in the coding might be from my porting from Scala to Java. It created a huge mess, but was necessary to move the mod forward. I like the Scala traits, but the syntax differences and the different data types were annoying and often made porting and even just troubleshooting more difficult than it needed to be. Some of the code I had to guess or come up with equivalents from scratch. I've contemplated bringing back some of the scala code just for the traits, but it opens up a can of worms with interoperability because of the different data and class types.

**Comment by eyeonus** [comment]
Yeah, that makes sense. I don't think that explains the inconsistent use of whitespace, though. I kind of want to push an update that literally does nothing but fix all the spaces to be tabs, and get all the indenting properly lined up.

**Comment by lehjr** [comment]
Whitespace differences are likely differences in IDE and OS. There were a lot of Windows users. Tabs are inconsistent across both whereas spaces are independent of OS and IDE

**Comment by eyeonus** [comment]
Ug. See, when I setup a git repo, I always set it to convert to unix-style to prevent that very issue. Git handles cross platform irritations like that automagically if you let it.

**Comment by lehjr** [comment]
try a PR with to the linux kernel project using tabs.

**Comment by eyeonus** [comment]
Naw. I'm good.

**Comment by lehjr** [comment]
LOL

**Comment by lehjr** [comment]
Personally, I don't care that much, as long as it looks consistent. The bigger issue is whether the code is easy to follow or not, because something that works today can easily be broken tomorrow, whether in porting or just by a forge update, like they did with 1.7.10 with fluids.

**Comment by eyeonus** [comment]
Agreed. I obviously haven't done much on here at this point for you to be able to see it, but I try to make sure my code is understandable and I leave helpful(?) comments to clarify if I don't think the code explains itself well enough.

**Comment by eyeonus** [comment]
Considering the state of the meter code before I worked on it, I'm considering looking through the whole project for other things of that nature and just doing a general code cleanup before I tackle anything else.

Or I might just clean things up in the course of doing the tackling. I haven't decided yet.

**Comment by lehjr** [comment]
Some of the documentation for the code is way off because it had gone through years of porting without updating the documentation. But for any major changes, now is the time while the mod is still in alpha. It might be a good time to decide if Numina needs to be a separate mod, or left like it is, or merged entirely back into MPS. It's only where it is now because it's easier to deal with changes both during development and by the end user instead of getting bug reports from people trying to mix and match old and new versions.

**Comment by eyeonus** [comment]
Numina was split off of MPS because she was planning on using that numina for another mod (right?), but that mod isn't in development and hasn't been for awhile. Unless you're planning on making another mod that uses Numina, I'd just leave it as is. That way if Machine Muse or some other person decides to work on Anima or some other mod that uses Numina, it'll be a simple matter to just split Numina back out again.

I'm betting merging it with MPS would make it more difficult to pull back out.

**Comment by lehjr** [comment]
Yes, it would make it harder to pull out, but it would make it easier to streamline related code instead of having things like the icons for the power fist handled in 2 different mods. I don't know, it probably isn't worth it right now to merge it in but it's something I would think about later on. As far as anyone else using Numina, I haven't seen anyone use it for anything outside of the FOV handler.

**Comment by eyeonus** [comment]
I'm fairly certain the vast majority of the code is in need of cleaning, so I'd say just leave it as is at least until the Numina code has been cleaned up, and likely the parts of MPS that interact with Numina.

**Comment by eyeonus** [comment]
Absolutely none of the powerfist code is in net.machinemuse.powersuits.event.ClientTickHandler .

That deals exclusively with the HUD items. The selector stuff is somewhere else.

**Comment by lehjr** [comment]
Yes, the client tick handler was in reference to that HUD mach up with the big circle. The power fist code I already pointed out:
https://github.com/MachineMuse/MachineMusePowersuits/issues/589#issuecomment-294469869

**Comment by eyeonus** [comment]
Oh, I misunderstood.

My problem right now is I have no idea how an event of the HOTBAR occurs. The code where the players' input is recorded is in the tick handler, but where's the code that deals with the input?

Where's the code that checks to see if the player is Shift+Scoll-Wheeling?

**Comment by lehjr** [comment]
net.machinemuse.numina.mouse MouseEventHandler

**Comment by lehjr** [comment]
There's also net.machinemuse.powersuits.control KeybindKeyHandler on the bottom that handles alternative keybindings for cycling the power fist tools.

**Comment by eyeonus** [comment]
Yes, there's what I'm looking for.

Okay. so this is going to be in a couple parts.

First part's probably the easiest bit. Replacing sneak+scroll with powerfist hotbar slot + scroll. Which means figuring out how to tell when the player is pressing one of the hotbar number keys.

The second part is going to be designing and implementing the radial menu. I don't even know where to start on that yet, but I'll cross that bridge when I get to it.

**Comment by lehjr** [comment]
Well, the keybinding handler is already there, so you could probably just get the keybinding for that slot and check if the item is in that slot.

**Comment by lehjr** [comment]
Wait, no, the mouse handler is in Numina, the keybind handler is in MPS -_-

**Comment by eyeonus** [comment]
Numina does have a keybind handler as well.

**Comment by eyeonus** [comment]
For one key.

**Comment by lehjr** [comment]
yes, but the mouse event and keypress events are not connected events.

**Comment by lehjr** [comment]
actually, you should be able to get the keybinding and use keybind.getIsKeyPressed()

**Comment by lehjr** [comment]
so, looks like this: http://www.minecraftforge.net/forum/topic/42089-1102-seting-up-keybinding/

**Comment by eyeonus** [comment]
Thank you for that.

I tried doing it that way and it was very finicky. Even though I was holding down the key the whole time, sometimes it would return false. The method I went with works loads better.

**Comment by eyeonus** [comment]
Is there any way to find out which hotbar slot is the active one? I'm not finding anything using Google, and I'd like to tidy down this mess of
`key == hotbarKeys[0].getKeyCode() || key == hotbarKeys[1].getKeyCode() || key == hotbarKeys[2].getKeyCode() || key == hotbarKeys[3].getKeyCode() || key == hotbarKeys[4].getKeyCode() || key == hotbarKeys[5].getKeyCode() || key == hotbarKeys[6].getKeyCode() || key == hotbarKeys[7].getKeyCode() || key == hotbarKeys[8].getKeyCode()`
to just check the active slot, rather than all 9.

**Comment by eyeonus** [comment]
In other news, except for a small quibble (see above), stage one is complete, and mode changing has been moved from "sneak + mouse-scroll" to "[powerfist hotbar slot] + mouse-scroll".
https://youtu.be/8RpgssApMhg

I've pushed it to my fork, but I'm going to hold off on the pull request until I get the radial selector thingy going.

**Comment by Bluexin** [comment]
```java
player.inventory.currentItem
```
Should give you the currently selected hotbar slot id (0-8) @aionys .

**Comment by eyeonus** [comment]
Oh yes. Much better. For some strange reason, I thought "currentItem" returned an item.

Silly me.

**Comment by Bluexin** [comment]
What? You mean you expected the method to return what it's name implies?? Fool!

**Comment by eyeonus** [comment]
I know, right? How dare I use logic!

**Comment by eyeonus** [comment]
Hey, where are the GUIs defined in this code? I'm having the devil of a time finding anything other than the resources used.

**Comment by eyeonus** [comment]
I'm trying to figure out where to put the code to draw the radial select thing, now that I've finally got the maths figured out.

**Comment by lehjr** [comment]
Problem is there is no completely central location for GUIs and the code for the powerfist module selection is in Numina

**Comment by lehjr** [comment]
The reason it is in Numina is because it was used in Anima too. MPS does deal with most of the GUIs but not all of them

**Comment by eyeonus** [comment]
Okay, maybe if I got a bit more specific, that'll help.

Right now, I have it so that when the hotbar key for the slot the power fist is in is pressed, it turns on a boolean I added to the input map:

net.machinemuse.powersuits.control.KeybindKeyHandler.java
`
            if (key == hotbarKeys[player.inventory.currentItem].getKeyCode()) {
            	PlayerInputMap.getInputMapFor([edited for clarity]).hotbarKey = true;
            }
`


In the same file, there's this:

`
if (key == openKeybindGUI.getKeyCode()) {
    World world = Minecraft.getMinecraft().theWorld;
    if (Minecraft.getMinecraft().inGameHasFocus) {
        player.openGui(ModularPowersuits.getInstance(), 1, world, 0, 0, 0);
    }
}
`

`void openGui(Object mod, int modGuiId, World world, int x, int y, int z)`

I'm trying to figure out where the GUIs are coded. They're apparently identified by number, so it might be an array?

[EDIT:I have no idea why the code tag isn't preserving whitespace, but I find it annoying.]

**Comment by eyeonus** [comment]
Also, the only thing handled by Numina is the code I'm replacing, so that doesn't matter in the slightest.

All the Numina bit does is detect if the mouse wheel was scrolled, and if the right key is being pressed, it calls the cycleMode function in the PowerFist class. All of the other code is on the powersuits side.

**Comment by lehjr** [comment]
net.machinemuse.powersuits.common.GUIHandler is about as good as you're going to get. The numbers are hard coded.

**Comment by eyeonus** [comment]
I don't have that file?

**Comment by eyeonus** [comment]
MPSGuiHandler. I see it now.

**Comment by lehjr** [comment]
yeah, that's the one

**Comment by lehjr** [comment]
little distracted today. Looking at the AE2 wireless module and looking at the "Scannable" module

**Comment by eyeonus** [comment]
Okay, I figured out where to put the code, Problem one solved.

It looks like I need to free the mouse without opening a GUI, though, since I want it to close when the player stops pressing the button, not stay open until the player presses escape.

I'll look around. I also need to figure out how to tell where the mouse cursor is on the screen.

[EDIT: No worries, mate. On your own time. You've got more important things to do, even only considering MPS and not including the rest of your life. It's cool. I'll figure this stuff out without your help, it just might take longer, so I appreciate when you do manage to have enough time to do so.]

**Comment by lehjr** [comment]
No worries.

**Comment by eyeonus** [comment]
So, still need to do the code for the actual selecting of the modes, but we've got progress:

[https://youtu.be/EYDNFWMlf7g](https://youtu.be/EYDNFWMlf7g)

**Comment by lehjr** [comment]
Looking really, really good.

**Comment by eyeonus** [comment]
Thank you for that. I'm currently looking through the MineMenu mod to see how the radial select is done in that one, once I figure out how to do it, I'll add actual functionality to that.

On that note, do we want to keep the mode indicator icons that get drawn over the hotbar?

**Comment by lehjr** [comment]
That's a really good question. If it's not something we need, then it's probably safe to eliminate it. Anima used it, and if it was more fleshed out I would try porting all of the changes to Numina that have happened since it was last  touched, but there's not enough there to even get a sense of direction the mod was going in. Other than that, I know of no other mod that uses Numina.

**Comment by eyeonus** [comment]
I was thinking of leaving the current mode icon so we have an indicator of which mode the fist is currently in, but I've no idea if we want to keep the other two or not, or if we want to keep the icon where it is, or move it somewhere else....

**Comment by lehjr** [comment]
hmm, the indicator.. right. Maybe just keep the one icon and ditch the others. The only other option would be to add the icon to the HUD, but not everyone uses that.

**Comment by eyeonus** [comment]
Sounds like a plan.

**Comment by eyeonus** [comment]
Hmm... MineMenu uses a GUI. Interesting.

**Comment by lehjr** [comment]
I'm not the least bit familiar with it :/

**Comment by eyeonus** [comment]
It's cool. I know MineMenu does basically what I want to do, so I'm looking at that mod's code to see how it's done there so I can get a feel for how to do what I want to do on this mod.

I thought I wouldn't be able to use a GUI because of the whole game pausing must press escape to close thing, but MineMenu uses a GUI, so it looks like I was wrong. This is good.

**Comment by eyeonus** [comment]
So, I got it working, mostly. For some reason the fist is getting switched back to the previous module on right-click.

I'm sure it's something stupid I did, I'll figure it out.

**Comment by eyeonus** [comment]
I think it might be because the server isn't being told to update the active mode, only the client is?

**Comment by lehjr** [comment]
that's probably it right there. There is a server packet for "mode changing item" in Numina.

**Comment by lehjr** [comment]
MusePacketModeChangeRequest

**Comment by eyeonus** [comment]
Functionality is complete.

Still need to figure out how to draw the closing animation, and it might need more graphic elements, like maybe the green circle from the mock-up, but this is basically finished, so I pushed it to my fork.

If you want, I can submit the pull request for this.

https://youtu.be/M4XxmS9xhXo

**Comment by lehjr** [comment]
Looks great :D

**Comment by eyeonus** [comment]
Get ready for a flood of "I can't switch modes" bug reports when this is in the release. :D

**Comment by lehjr** [comment]
I'm going to put it a clearly marked alpha.

**Comment by lehjr** [comment]
just got an index out of bounds exception

**Comment by eyeonus** [comment]
What were you doing when it happened?

Do you have the log?

**Comment by lehjr** [comment]
https://gist.github.com/lehjr/068808896a3093ecf4fdcc5306af0a52

basically just loaded the power fist up with modules and tried pressing the hotbar number for it to select the power fist.

**Comment by eyeonus** [comment]
I got it. Give me a second to do the pull request.

**Comment by eyeonus** [comment]
Done.

**Comment by lehjr** [comment]
Testing now.

**Comment by eyeonus** [comment]
I can guarantee that exception will never happen again. I wrapped it in a method that handles out of bounds indexes by returning null.

**Comment by lehjr** [comment]
has a weird flickering thing where it opens, then the closes rapidly if you hold the hotbar key. Stops if you press another key.

**Comment by eyeonus** [comment]
I'm not getting that.

You have to hold the hotbar key to keep it open. Releasing the key closes it.

I'd only expect the behaviour you're talking about if you were continually pressing and releasing it.

What are the steps to reproduce this consistently, becuase I'm not seeing it at all.

**Comment by eyeonus** [comment]
In trying to get that to happen, though, I did notice that the menu opens when holding down any hotbar key in some situations. I'm fixing that now.

Any update on how you're getting your thing?

**Comment by eyeonus** [comment]
I've fixed the thing I saw. It may have fixed your issue too. Let me know if you find anything else.

I haven't, but that doesn't mean there isn't something else I missed.

**Comment by lehjr** [comment]
which thing would that be? My current goal was to create a module for "scannable", but I think it's going to at least need a way to be able to open the GUI from another mod.

**Comment by eyeonus** [comment]
The flickering thing you were talking about I can't reproduce.

**Comment by lehjr** [comment]
I recorded a video of it

**Comment by eyeonus** [comment]
Is it still happening since the last pull request merge?

Video link?

**Comment by aionys** [comment]
Is it still happening since the last pull request merge?

**Comment by lehjr** [comment]
yes: https://vimeo.com/218825525

**Comment by lehjr** [comment]
not apparent in the video, but when it stopped glitching was when I pressed another key while holding the hotbar number key

**Comment by eyeonus** [comment]
I can tell you three things:
1) That's really weird.
2) That doesn't happen for me at all.
3) The call to close the gui only happens when the key isn't being pressed anymore:
`    public void update() {
        super.update();
        if (!Keyboard.isKeyDown(Minecraft.getMinecraft().gameSettings.keyBindsHotbar[player.inventory.currentItem].getKeyCode())) {
        	//close Gui
        	try {
    			keyTyped('1',1);
    		} catch (IOException e){}
        }
    }
}`

Maybe it's something to do with your keyboard?

**Comment by lehjr** [comment]
no other issues with the keyboard.

**Comment by eyeonus** [comment]
I don't know what to tell you, man. I am not getting that behaviour at all, so I have no idea why you are. The only thing I can think of is something to do with your keyboard. Either the physical keyboard itself, or the driver maybe. If it's not that, I'm lost.

For some reason Minecraft is being told that you're not holding down the hotbar button when you are, and that's why it's closing.

I can't reproduce it, so I can't figure out what's causing it, and until I do, I can't fix it.

**Comment by lehjr** [comment]
I'll have to see what I can do with it then. Driver really isn't likely, just an ordinary USB keyboard on Linux. It could be a key handler in another mod, I don't know yet.

**Comment by lehjr** [comment]
oops

**Comment by eyeonus** [comment]
The code to decide whether to close the gui is at net.machinemuse.general.gui.GuiModeSelector#update()

It could be because Linux, then. I'm on Windows here.

I had an idea that may help, and at the least doesn't break anything.

**Comment by lehjr** [comment]
with PS2 keyboards, there was a BIOS setting called typematic rate setting. I don't think there's any such setting for USB keyboards

**Comment by eyeonus** [comment]
I have no idea. I was just thinking that it might be that the reason I can't reproduce it is because I'm on Windows, and Linux and Windows handle keyboards differently, so your Linux box is either doing something my Windows box isn't, or isn't doing something mine is, for the simple reason of different OS environment.

**Comment by lehjr** [comment]
could be LWJGL too.

**Comment by eyeonus** [comment]
If LWJGL is different on Linux than it is on Windows, I suppose.

**Comment by lehjr** [comment]
LWJGL has different handlers for different OSes

**Comment by eyeonus** [comment]
Right. Duh. Ignore the stupid coming from my face, please.

**Comment by lehjr** [comment]
the current lwjgl for Minecraft is outdated. It still supports Windows 95

**Comment by eyeonus** [comment]
Weren't you saying you were thinking of updating this guy to the latest lwjgl? Do you think that would fix this weirdness?

**Comment by eyeonus** [comment]
Because now you've mentioned it, it does seem most likely to me that this is a lwjgl thing.

**Comment by lehjr** [comment]
I wanted to but it's a ton of effort with no reward. You would basically have to rename every LWJGL file and write wrappers for everything just to not edit Minecraft.

**Comment by eyeonus** [comment]
Damn. I thought maybe you could hide it locally so that only the mod itself saw it.

**Comment by lehjr** [comment]
no, it's entrenched into MInecraft itself. It's a project just getting Minecraft to run with it without mods.

**Comment by eyeonus** [comment]
At least we know it works for Windows users....

I wonder if the same thing happens when it's run on a Mac?

**Comment by lehjr** [comment]
good question.

**Comment by lehjr** [comment]
playing around with the code. Noticed that if you comment out everything in update() you can use the escape key to close the selector.

**Comment by eyeonus** [comment]
Yeah, that's true regardless.

In fact, what the update does to close the gui is tell it the escape key has been pressed.

**Comment by lehjr** [comment]
but it stays open without having to hold the key, meaning no glitch.

**Comment by eyeonus** [comment]
Yes, that's because you commented out the code that closes it when the key is no longer being held down.

The glitch is being caused by something in the Keyboard.isKeyDown(...) call.

**Comment by lehjr** [comment]
tested in Windows and same thing. Released today as an alpha to see how much of an issue this is.

**Comment by lehjr** [comment]
Turned out to be "rapid input mode" setting on my keyboard, though such a thing was not apparent. Guess reading the manual for a keyboard can actually help sometimes.

**Comment by eyeonus** [comment]
I figured it was something with your keyboard. ;)

**Comment by eyeonus** [comment]
What's the difference between the alpha and 118?

**Comment by lehjr** [comment]
118 is before the commit for the radial selector. I know, kinda backwards, but realized after that I had forgotten to do a build with the ae2 terminal and the techreborn recipes.

**Comment by eyeonus** [comment]
I don't like that the mode indicator is so far away from the actual slot, especially with armor, but I don't know anywhere better to put it.

**Comment by lehjr** [comment]
It's OK for now. Still waiting to get some feedback on it.

**Comment by eyeonus** [comment]
I didn't move it or anything. It's always been there.

**Comment by lehjr** [comment]
Yeah, it's just the icon wheel that was there minus the other icons. It's OK for now. Eventually it could be a HUD thing or ... well, not really sure. An orphaned icon is kinda odd by itself.

**Comment by eyeonus** [comment]
It's a simple matter to put that bit back to how it was so it's not so lonely, but it's still way up there.

I thought about putting it in the hotbar, like peaking up out of one of the corners, which can be done with the drawIconPartialAt() or whatever it's called, but everywhere I tried in a mock up in gimp was pretty bad.

**Comment by lehjr** [comment]
not worrying about it atm. We'll see if there's any feedback and go from there. In the mean time, I'm still looking at the scannable module. Not sure if you've seen the mod, but it's pretty cool.

**Comment by eyeonus** [comment]
I just looked at it. It's interesting. Hopefully the api lets you open the gui.

**Comment by lehjr** [comment]
currently no. Gonna need some work for that. It really isn't set up to be used externally.

**Comment by eyeonus** [comment]
Adding sneak right-click functionality wouldn't be hard to do with the radial selector, since it frees up that button, at least.

And it would actually be useful for other things, like the omni wrench, as well.

**Comment by eyeonus** [comment]
Speaking of the OmniWrench, it'd be cool if it was possible to replace it with the Morph-O-Tool, but I'm willing to bet that's either too much effort to be worth it, or just not possible in the first place.

**Comment by lehjr** [comment]
I had no idea what that even is and had to look it up. Interesting. Replacing the OmniWrench would be nice to be honest.

**Comment by eyeonus** [comment]
Yeah, it's a great tool. The Akashic Tome, I believe it's called, by the same guy, is the same thing, for books.

They're both supremely useful.

**Comment by lehjr** [comment]
Looks like only 12 downloads for this new code, and no feedback. This is probably because I released the alpha and a new release together. So I am putting out a new release today to fix Forestry integration (without radial selector code), and then a new beta after with the new code in the hopes that people will actually try it. I'd put the new radial selector code in a release, but without feedback I don't know how well received it will be.

**Comment by eyeonus** [comment]
Yeah, I figured that would happen.
Before you do that, though, I had a thought.

Could you put a chat message on load mentioning the new mode selection method?
I don't know how many people would see it, but I think it'll reduce the number of "shift-scroll don't work" bug reports, since those that do see it will know what's going on.

Something simple like "Modular Powersuits: Power Fist mode selection is now done by holding down the hotbar key the fist is in. The old method of scrolling the mouse while sneaking has been removed."

**Comment by eyeonus** [comment]
As far as feedback, it's working perfectly in my live world, and I find it immensely less annoying, but I'm not sure my feedback counts.

**Comment by lehjr** [comment]
It's probably not that big of a deal, I just want to get some feedback before forcing a gameplay change. On the other hand, it will be in 1.11.2 just like you have it. Actually, it will probably be one of the few things that doesn't get changed.

**Comment by eyeonus** [comment]
No worries.

**Comment by eyeonus** [comment]
Got nearly a thousand downloads on the latest beta, so it's looking good. Any feedback?

**Comment by lehjr** [comment]
Over a thousand now, yet not a word of feedback. I really don't want to force it on users in the middle of a release cycle, but I also don't want to keep pushing 2 separate builds for one update. And really, it doesn't make sense to do 2 separate builds anymore because users are just going to pick the latest one anyway. 

It's been nearly 2 weeks, and no feedback, good or bad. I guess it's time to just release it and see what happens.

**Comment by eyeonus** [comment]
Lack of feedback may mean that everyone's happy with it?

Or at least not unhappy enough to give a rat's. :)

**Comment by lehjr** [comment]
I was thinking that it was more that no one has tried it yet. I do that myself; install a bunch of mods, and barely use any of what I've installed, largely because of time constraints. Anyway, I'll be pushing out another update today. We'll see how it goes.

**Comment by eyeonus** [comment]
Any feedback at all on this yet?

**Comment by lehjr** [comment]
None. Users have practically gone into stealth mode. It's in the last release. Still no word. Oh well. It will be in the 1.12 as well. Probably one of the few things I keep.
