### ISSUE TITLE
Keybind indicators

### ISSUE THREAD

**Issue by MachineMuse** [MachineMuse/MachineMusePowersuits#590]
Rather than spamming chat, let's make it a HUD element

**Comment by EzerArch** [comment]
Yes.

From the issue #589, with some rephrasing:

All MPS modules would be organized like this:

* **Power Fist modules:** i.e. weapons and tools, go to the radial selector. If there are too many, they can be separated into profiles such as "Battle", "Work" etc.

* **Suit modules:** the player can choose to keybind or to control by turning them on and off with mouse-click on screen (to avoid too much keybinding). These modules can get a HUD element/indicator.

But what if the player install many modules? I'm afraid they all will clutter up the screen along with other UI elements from other mods (e.g. minimaps, meters). The solutions may be to let the player enable or disable which module indicators should be put on the HUD.

I suggest making the "Keybinds" window into a module manager where you can turn on and off modules by mouse-click, set keybinds (incl. NONE) and enable/disable show module icon on HUD. Instead of using hooks to assign the key, each module would be have a bar like this:

![image4417-1](https://cloud.githubusercontent.com/assets/6743303/9570907/c07cfc24-4f6b-11e5-9cf9-ea12f533a99d.png)

Once the player has enabled the modules to have a module indicators, he can then drag the module indicators where they best fit. The module indicators will gray out if their modules were turned off by keybind or mouse-click on the module manager, or because the suit ran out of energy.

**Comment by MachineMuse** [comment]
I like your suggestion but it's too much work when I'm trying to finish this up quickly.

Instead I implemented it like this:
![HUD demo 1](http://puu.sh/k3ZO1/f72f7d22c1.jpg)
![HUD demo 2](http://puu.sh/k3ZRI/6a3ad47937.jpg)

Currently you can move it around using configs. Maybe I'll add an interface to change the positioning in-game later.
