### ISSUE TITLE
[Bug]Duplicated Recipes

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#599]
With this recipes settings, if I have thermal and vanilla, I have duplicated recipes for some items, for example:
![test](https://cloud.githubusercontent.com/assets/8685029/9564919/fb54eb46-4eb6-11e5-8995-1d7b3e81f920.png)
Now, this thing could be fixed in two modes:
1) Change those recipes for thermal
2) Add a new recipe file, ex. mps-default.recipes (this file will be extracted by default only the first time) and add this recipes into this file, and delete from thermal/vanilla recipe files
@MachineMuse tell me what you think about it.

**Comment by MachineMuse** [comment]
I actually had the recipes different to begin with, but I changed them because I didn't know enough about the new Thermal Expansion to decide on appropriate recipes for things. So if you can put a different appropriate recipe, then it should be good.

BTW, the recipes aren't intended to be used together. Vanilla resources are almost all easier to obtain with a mod, that's why I made the other recipe files to make it an appropriate progression for that mod. e.g. with ThermalExpansion/IC2/etc. you have ore doubling, so you can get a lot more metals.

I might write a thing to check if two recipes are duplicates though. It hopefully wouldn't be too much overhead.

**Comment by Xen1290** [comment]
Thanks for the answer!
By the way, the recipes are very random, I'll try to balancing.

**Comment by Adaptivity** [comment]
@Xen1290 Also, convert all recipes to use oredict. I wanted to do it myself but since you are going to balance them it shouldn't be hard to you.

**Comment by Xen1290** [comment]
Already done @Adaptivity

**Comment by Xen1290** [comment]
Fixed with #603

**Comment by MachineMuse** [comment]
Still going to make it scan for duplicates. I should make it a config option so if people have a lot of JSON recipes they can turn it off to save load time.

**Comment by Xen1290** [comment]
Oh ok, sorry!

**Comment by MachineMuse** [comment]
done by Numina 82a947948b58015912d6d8fabf1383cd3e31de6e
