### ISSUE TITLE
Unable to craft items using IC2 recipes

### ISSUE THREAD

**Issue by jeremyfry** [MachineMuse/MachineMusePowersuits#610]
Unable to craft items using IC2 recipes

NEI does not show recipes for many of the items (Helemet, Tinkers Table, etc) but show incomplete recipes for others (wiring shows only redstone, not the gold cable to either side). 

The recipes json file did get copied into the config but some of the recipes in it don't work. I was able to craft wiring using the ic2 recipe with gold cable. However trying to craft a tinker table using: [null, emerald, null],[iron plate, electronic circuit, iron plate],[null, basic machine casing, null] did not work though that seemed to be recipe in the mps-ic2.recipes file that is in the config.

I upgraded my NEI and related mods to the latest and that doesn't seem to have helped.

**Comment by aionys** [comment]
The error says it doesn't know what a "null" is. In Minecraft's recipe handler, for when writing a mod, empty spots in the recipe are just left blank, like in the furnace recipe: [stone, stone, stone][stone, , stone][stone, stone, stone]

Try removing the "null"s in the recipe, for example changing the recipe from "[null, emerald, null]" to "[ , emerald, ]" and see if that works.

**Comment by Xen1290** [comment]
Can you paste the entire recipe? Sorry but I can't understand. By the way, with latest version the recipes have been rewritten, I Suggest to delete the old recipes and reload the game with latest version of MPS And Numina to get the new And fixed recipes. And then modify the recipes ad you want. Sorry for possible english mistakes

**Comment by jeremyfry** [comment]
It's a new server I'm setting up so recipes should be up to date (downloaded today and installed today). Here's the tinker table recipe as it appeaars in my mps-ic2.recipes file.
```
		"ingredients" : [
			[ null, { "oredictName" : "gemEmerald" }, null ],
			[ { "oredictName" : "plateIron" }, { "oredictName" : "circuitBasic" }, { "oredictName" : "plateIron" } ],
			[ null, { "registryName" : "IC2:blockMachine" }, null ]
		],
		"result" : {
			"registryName" : "powersuits:tile.tinkerTable"
		}
```

I tried modifying the recipes I see in the json file to make sure they would get updated in game. I changed basicPlating (which does show up in NEI) to use gold ingots instead of iron and that change was reflected in the client after a server restart, though I did see both the modified and original recipe as valid options. 

After getting the correct recipe into the crafting table the server throws this error:
```
[21:25:32] [Server thread/WARN] [MachineMuse]: Unable to load powersuits:tile.tinkerTable from oredict
```

I've also remove the earlier exception I was seeing from NEI as the exception handles without MPS loaded.

**Comment by Xen1290** [comment]
"I tried modifying the recipes I see in the json file to make sure they would get updated in game. I changed basicPlating (which does show up in NEI) to use gold ingots instead of iron and that change was reflected in the client after a server restart, though I did see both the modified and original recipe as valid options."

Yes, this is a bug, I forget to report it. 

So I don't know what's going on, are you using ForgeEssentials/Cauldron/KCauldron or similar? If you have one of this option, test with a forge server. Also please test in singleplayer and tel me what will happen. Thanks, also @MachineMuse can help us

**Comment by MachineMuse** [comment]
Only the server should be loading recipes (integrated or dedicated). The client receives recipes from the server; thus you only need the recipes files on the server. There might be a way to remove recipes after starting, but that can cause problems with other mods (I know TE caches furnace recipes early on, so if the recipes are changed with Minetweaker, the Redstone furnace ignores them). So unless I add something like that, it will keep any recipes received from single- or multi-player until the client is restarted.

> [MachineMuse]: Unable to load powersuits:tile.tinkerTable from oredict
This shouldn't happen unless you have the output field set to 
            "oredictName" : "powersuits:tile.tinkerTable"
rather than "registryName" ?

**Comment by MachineMuse** [comment]
BTW Aionys, the JSON parser changes blanks to nulls, so what you put is functionally equivalent. Numina handles null in input boxes as blank spaces.

**Comment by jeremyfry** [comment]
@MachineMuse The oredict error was probably from me trying to debug the recipes and see if I could load in a simple recipe to make the table.

Since there's been a lot of different angle on this, let me just rebaseline with the problem I'm having and what I've been able to figure out so far.

Happening in both single player and multiplayer, with the following mods: 
Forge 10.13.4.1448
IC2 2.2.628
Powersuites 0.11.0.264
Numina 0.4.0.100

Trying to craft the TinkerTable with the following items:
```
Display Name, Item ID, Unlocalized Name, Item Class
Emerald, minecraft:emerald, item.emerald, net.minecraft.item.Item
Basic Machine Casing, IC2:blockMachine, ic2.blockMachine, ic2.core.item.block.ItemMachine
Electronic Circuit, IC2:itemPartCircuit, ic2.itemPartCircuit, ic2.core.item.ItemIC2
Iron Plate, IC2:itemPlates, ic2.itemPlateIron, ic2.core.item.resources.ItemPlate
```
Using the following recipe:
```
		"ingredients" : [
			[ null, { "oredictName" : "gemEmerald" }, null ],
			[ { "oredictName" : "plateIron" }, { "oredictName" : "circuitBasic" }, { "oredictName" : "plateIron" } ],
			[ null, { "registryName" : "IC2:blockMachine" }, null ]
		],
		"result" : {
			"registryName" : "powersuits:tile.tinkerTable"
		}
```

Fails silently. No errors or anything, the recipe is uncraftable. I checked my oredict and IC2:itemPlates:4 is listed as plateIron.

**Comment by Xen1290** [comment]
You ade using an piratesco version of numina and MPS, download the latest beta version in curseforge

**Comment by jeremyfry** [comment]
Looks like Numina needed to be updated past 0.4.0.113. That fixed the issue.

**Comment by jeremyfry** [comment]
Oh and thank you to everyone for helping me figure this one out.
