### ISSUE TITLE
Crash on Startup with enhanced portals, doesn't occur on old versions

### ISSUE THREAD

**Issue by Darkmega18** [MachineMuse/MachineMusePowersuits#614]
Hi machinemuse, I've got this crash here: http://pastebin.com/gYYm4Pj6

This crash occurs when I used the latest versions on curseforge in my modpack. The versions that I had previously - before combing through and doing a big set of mod updates and noticing all these new actual releases is: mps build 118, and numina 101. the 5 or so latest releases have this crash which occurs during phase 2 of loading, as far as the forge loading screen is concerned, but I don't think I want to shift through 20 or so old versions to try to find where it last occured when you could possibly glance at it and find the reason.

Enhanced portals has never blown up before like this and upon downgrading back to those two versions mentioned the game loads. only reason I don't just sit back there on them now is cause I found a different crash which only blows up the client when done on the server, which just so you know about it, is this crash: http://pastebin.com/TCGnByet which is from the old versions and I'm not sure if it has continued to work cause I can't even get my client to pass the latest ones before blowing up. 

Regardless, back to the first crash:
 the server owner has said that the server is able to load itself perfectly fine with the latest versions, despite the client blowing up on phase 2 of loading with that. So please take a look at that. I'd very much like to have modular powersuits in my pack again. :)

**Comment by Xen1290** [comment]
@Darkmega18 
Try to reset config folder if you haven't modified it(custom recipes etc), this should fix nei crash, because with latest version the recipes system has been redone.

For the first crash, are you sure that is caused by MPS/Numina ?
Enhanced portals has nothing to do with MPS, here you can see the wrench interfaces:
https://github.com/MachineMuse/MachineMusePowersuits/blob/7c3cd2a825bb0be090956d8fd99acd2a411c1ff6/src/main/scala/net/machinemuse/powersuits/item/ItemPowerFist.scala

Also in the first crash, the crash log says:
UE	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
E = Errored
Sorry for possible english mistakes!

Also update Numina to latest beta version.

**Comment by Darkmega18** [comment]
I just pointed it at modular and numina cause it only occurs when they're in the pack. yes they have nothing to do with it, but the coincidence is is that the crash doesn't happen at all if they're not in the pack strangely enough.

and yeah, I had half an idea of what to change. I had only divided all the weight numbers in half and attempted to half all the power costs of stuff in the config. so shouldn't be too hard to redo if I gotta reset configs. but that still leaves the crash on start up, so I'll keep that in mind for when I can actually load my game with them in. :)

**Comment by Xen1290** [comment]
Oh, ok! By the way, I think only @MachineMuse can figure out the first crash. I helped you on what I know

**Comment by MachineMuse** [comment]
I'm not sure what's happening exactly but I checked the Enhanced Portals code and they are including the interface directly (which used to be the only way to do it) instead of using @Optional which is the new (better) standard. It might be something to do with that.

In any case, please report this to the Enhanced Portals devs ( https://github.com/enhancedportals/enhancedportals/issues ) and as a stopgap solution, try adding Buildcraft to the pack so that the API is fully present?
