### ISSUE TITLE
Only Helmet showing visuals - the rest of the armor looks like old Western underwear...

### ISSUE THREAD

**Issue by eslachance** [MachineMuse/MachineMusePowersuits#625]
I've got the very latest version of MPS (previous version's recipes didn't work!) on 1.7.10 in a custom pack on Curse. 

The "Visuals" tab in the Tinker Table only seems to modify the Helmet, all 3 other armor parts do not show any changes. And, they kinda look like the full-body underwear we see in old Westerns... 

![2015-09-14_16 37 46](https://cloud.githubusercontent.com/assets/643344/9861314/7eaa1f58-5aff-11e5-8b07-fbffec1d8656.png)

What am I doing wrong?

**Comment by MachineMuse** [comment]
Important rule for reporting issues: say exact version numbers, not just 'latest'. Include version of numina as well please.

That aside, it's the model for undyed leather armor, which shouldn't be showing up as of build #192 of MPS. Are you using any custom animations mods or anything?

**Comment by eslachance** [comment]
My apologies. The MPS version is 0.11.0.281, Numina is 0.4.0.119. I am, in fact, using Animated Player Mod. If that interferes, I'll remove it to test.

**Comment by MachineMuse** [comment]
Yeah. Sadly, I can't make a special case for Animated Player Mod because it changes the underlying model, which the armor model uses as a reference to know where to render the armor parts. I was able to make smart moving/renderplayerapi compatibility relatively painlessly because it keeps the same 6-box model and just makes them move in new ways.
