### ISSUE TITLE
Crash with ender io

### ISSUE THREAD

**Issue by MJRLegends** [MachineMuse/MachineMusePowersuits#653]
See https://github.com/SleepyTrousers/EnderIO/issues/3025

**Comment by lehjr** [comment]
The QMX fork is dead and unsupported. build 284 was accidentally built with older source essentially creating an outdated build with a new number, which makes build 283 the most updated build. If you want a build with the addons integrated, I have this here, which will be in the next offical release once the build.gradle is updated to pull the required libraries: https://github.com/lehjr/MachineMusePowersuits/releases/tag/283d

**Comment by MJRLegends** [comment]
build 284 should be removed then

**Comment by lehjr** [comment]
it should be, but only @MachineMuse can do that.

**Comment by MJRLegends** [comment]
Oh ok

**Comment by K4N0** [comment]
QMX latest version fork still works, i have everything up to date. Was there something new added to Powersuits?

**Comment by lehjr** [comment]
The QMX version is built on now outdated libraries and once you update those libraries, things will go horribly wrong. As for what has been added to the original MPS since then, I'm not entirely sure; there seems to be a wrench of some sort and a chisel module compatible with both versions of chisel. The build I posted also has the addons built in, and is compatible with AE2 RV2 and RV3 as well as the latest extra cells builds. 

Edit: the QMX Addons fork breaks in AE2 and EC2 somewhere in RV2. I was using my own version of it, but it wasn't worth maintaining a fork of the addons only compatible with an abandoned fork of MPS. Some of the QMX fork has been merged back into MPS and Numina.

**Comment by K4N0** [comment]
Hmm, I'm going to have to do some testing. Thanks

**Comment by Xen1290** [comment]
@Badcholo @MJRLegends  try with ModularPowersuits-0.11.0.289 and Numina-0.4.0.131 that you can find in CurseForge. These builds contains also MPS Addons and the recipes updated, and also the things that lehjr explained above. And Make sure to backup and reset the machinemuse config folder.
