### ISSUE TITLE
1.8.9 version crash when added to skyblock pack of mine

### ISSUE THREAD

**Issue by SDUBZ** [MachineMuse/MachineMusePowersuits#706]
heres the crash hope you fix http://pastebin.com/dLGU2sUp

**Comment by lehjr** [comment]
Early alpha means expect things to be broken, the mod is under heavy development. In other words, do not expect polished releases that play well with other mods. Do not use with maps that you want to keep. 

The log says it is caused by a different mod, but it's probably more of a mod interaction issue.
Again, it's a bit early to be throwing this mod in with a bunch of others and expecting it to play well with others.

> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@23d23d98 from coremod AppleCore
