### ISSUE TITLE
Realistic Component Mass

### ISSUE THREAD

**Issue by CJL48** [MachineMuse/MachineMusePowersuits#716]
At the moment, installed physical components (those that have a weight/mass associated with them: at the moment. have the same component cost regardless of the amount of weight installed. Although many of the energy using components use a similar system, I feel that it's easier to justify increasing power use without installing additional components. As such, I propose an alternate system of weight customization- adding/removing 'extra' components to increase the effect of physical components.
For example, each unit of armor/heat plating would cost 1/5 the amount is does now, but for 5 points of armor you would need 5 of the component.
This would make energy storage and generation more expensive, though I feel that this would actually help balance the mod, as well as encourage use of higher tier batteries.
This isn't a particularly important alteration, but I feel that it would be nice to have.
As an addition, perhaps making it easier/possible to select round power/effect levels while tinkering?

**Comment by flowtender** [comment]
You can add a Mass field to them by creating a new tradeoff in the config file, iirc. I didn't properly flesh out the feature because I found that a lot of players didn't really enjoy having to pay attention to their mass or didn't understand how it was affecting them.

In general, rather than trying to balance the mod against the huge ecosystem of mods that exists (which is an equation with no valid solution), I decided to try and make things configurable so that individual pack authors could tune it to be balanced within the context of their particular arrangement of mods.

That, combined with the fact that I haven't been interested in Minecraft for close to a year now, and lehjr has sort of taken over the arduous task of porting it, means this probably won't happen ever. Sorry.
