### ISSUE TITLE
I can't access Jenkins

### ISSUE THREAD

**Issue by 2chnera** [MachineMuse/MachineMusePowersuits#721]
i can't accessbJenkins.
Why???

**Comment by 2chnera** [comment]
and i can't download recipie file

**Comment by lehjr** [comment]
The Jenkins build server has been down since mid April: 
http://forums.technicpack.net/topic/295323-jenkins-build-net-is-down/

I have no idea what is going on with it. Maybe @MachineMuse knows. I haven't been using it since I don't have access to it and haven't needed it since 1.8.9 requires some changes. 

1.7.10 recipes can be found here:
https://github.com/MachineMuse/MachineMusePowersuits/tree/experimental/src/main/resources

1.8.9 recipes can be found here:
https://github.com/lehjr/MachineMusePowersuits/tree/1.8.9/src/main/resources

**Comment by 2chnera** [comment]
Thank you
