### ISSUE TITLE
Can't change Power Fist color

### ISSUE THREAD

**Issue by AllySummers** [MachineMuse/MachineMusePowersuits#728]
Hi.

I seem to be unable to change the color of my power fist. I am able to change the power armor, although not the fist.

Here are screenshots: http://i.hewlothere.me/eF6Wt.png http://i.hewlothere.me/QOHbB.png

I have a fully upgraded fist EXCEPT for Prototype OmniProbe, ExtraCells Wireless Fluid Terminal and AppEng Wireless Terminal. I also have the elite battery.

**Comment by AllySummers** [comment]
(Sorry if I need to make another issue for this)

I was also wondering what happened to the option for old auto-feeder, where it would store food?

**Comment by Xen1290** [comment]
Yeah, i think @lehjr(the only developer right now) is aware of this bug, but i think he hasn't the time to fix bugs from 1.7.10.
He is working for the 1.10.2 version.
For the auto-feeder, i never used it before, so I don't know.

**Comment by lehjr** [comment]
Yes, 1.10 is the only thing I have time to focus on right now. I'm mostly tied up with adapting to the rendering changes between 1.7.10 and 1.10.2 and trying to put out something closer to the 1.7.10 version  instead of the mess that the 1,8,9 version was.

The auto feeder should pull from any inventory slot in your inventory. It only consumes as needed. 

Btw, I wasn't able to see anything in those screenshots related to Minecraft at all.

**Comment by lehjr** [comment]
power fist coloring will return in MPS 1.10.2 alpha 11.

**Comment by DoomRater** [comment]
Power Fist coloring must be one of those things that just falls to the wayside...

**Comment by lehjr** [comment]
Since many versions ago, you can change the color of individual parts rather than the whole thing. This was changed due to rendering/model changes.

**Comment by DoomRater** [comment]
Turns out my issue was that attempting to change the edit power fist value from within Minecraft didn't save.  My bad.
