### ISSUE TITLE
Power suit in 1.7.10 still have a lot of incompatibilities

### ISSUE THREAD

**Issue by lightning02** [MachineMuse/MachineMusePowersuits#729]
This mod models are surely awesome but the various incompatibilities make it a nerf somehow, even worthless, I know that the actual developer is working hard and the wish to modding for 1.7.10 is not very high in our days but it would be nice let powersuit for 1.7.10 as a milestone in the minecraft modding community.

I noticed an incompatibility with Enviromine, since the heat plating doesn't prevent the overheating from enviromine.
I also noticed an incompatibility with Lycanites's mobs, since you can be damage regardeless what module you wear on, like the mobs ignore your armor.
This doesn' happen for example with Draconic Armor that seems to work fine :/

Actually using version: ModularPowersuits-0.11.0.300

http://imgur.com/a/LwIy2

I hope that something can still be done...

**Comment by lehjr** [comment]
Unfortunately, it is impossible to support every mod out there. As it stands, just getting a 1.7.10 workspace up and running is a pretty hefty task in itself because of the number of mods already supported, and made worse by the dangerous mix of abandoned mods and frequently updated mods. 

Since I am the only person working on this mod, with both limited time and skill, I simply cannot even support multiple Minecraft versions. As such, the only way I can continue to progress on 1.10.2, is to abandon everything prior completely. If I get too wrapped up in supporting past versions, this mod will not have a future.

**Comment by Xen1290** [comment]
Need special support for these things, and I think @lehjr (the only developer at the moment) hasn't the time to add this in 1.7.10, he is working for the 1.10.2 version of the mod. Maybe when he will finish with 1.10.2, or maybe if someone can make a pull request to add this support.

EDIT: lehjr has preceded me.

**Comment by lightning02** [comment]
Mhm... I see... I will try to follow Xen advice, also I willl try to kindly ask to these mod developers to help raising this compatibility with a pull request or something like that... let's hope for the better... this is honestly the most worth armor to craft in minecraft

**Comment by eyeonus** [comment]
Ooh yeah. I'm going to be the first guy to sign up for the 1.10 beta when
there is one, that's how much I love this mod.

**Comment by Xen1290** [comment]
@aionys follow this issue https://github.com/MachineMuse/MachineMusePowersuits/issues/725 for 1.10 updates

**Comment by lehjr** [comment]
1.7.10 support has ended, sorry.

**Comment by lightning02** [comment]
but... how.. why? D:
1.7.10 is still largely used among people

**Comment by eyeonus** [comment]
Because he's the only one working on it, and he doesn't have enough time to
work on getting it working for 1.10 AND maintain 1.7.10, so he's
prioritizing.

He said he will most likely back port the biggest big fixes, so take heart.

On Mar 27, 2017 10:23, "lightning02" <notifications@github.com> wrote:

but... how.. why? D:
1.7.10 is still largely used among people

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MachineMuse/MachineMusePowersuits/issues/729#issuecomment-289506130>,
or mute the thread

**Comment by lehjr** [comment]
@aionys exactly. Only so many hours in a day means only so many man hours available. Not to mention how much more complex things have become to get anything just to render. I'm still trying to get models to load and properly bind a texture to them without hacky workarounds. And honestly, the number of downloads for 1.7.10 releases isn't all that impressive. It was time to move on a year ago.

**Comment by lightning02** [comment]
The downloads aren't many because alot of people already downloaded the mod, that's all..
You could do a patreon account if  you already haven't one (maybe with some nice thing dedicated to the top donators), so people could support you even if they are just still using  the "old" version of the mod

**Comment by lehjr** [comment]
OK, but if they aren't downloading those newer versions, then they aren't using them and they aren't getting those versions with things fixed in them, which is the point I'm trying to make. Why spend the time to create fixed versions that no one is using? And sure, a patreon account would be great, especially when I spend so much time working on the mod, but it still would not add more hours to the day. Which is the biggest issue. Sure, money is great, but fixing bugs for 4 people really doesn't seem rewarding, nor does addressing the same issues over and over again from people mixing and matching old and new mods and expecting everything to work perfectly after the API changes half a dozen times or more. And I still get bug reports with no useful information, like this one: https://github.com/MachineMuse/MachineMusePowersuits/issues/766 where the user files a bug report and disappears without any further input. 
But the long and short of it is that I've seen far more demand from users for newer versions than I am for 1.71.0 support. And anything past 1.7.10 is a nightmare. Rendering changes alone have made everything tedious. 1.7.10 has been milked to death. Even Thermal Expansion has releases for 1.10.2 now, and MFR is in the process of being ported. Mekanism already has 1.10.2 ports. Even Applied Energistics has 1.10.2 ports. And there are plenty of others. There really is no reason to cling to 1.7.10 when it means nothing but death for this mod. I can either sit here and milk 1.7.10 for every last drop it is worth, or I can reach for the future with both hands. I cannot do both.
