### ISSUE TITLE
Advanced Solar Generator Crash?

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#734]
I was just flying around with my jetpack, no idea why it suddenly crashed.

https://gist.github.com/Zsashas/abb97e1fb7ae43fbccc8c26e5465a18e

**Comment by lehjr** [comment]
This is an old crash that really should have been dealt with a long time ago. It has to do with checking to see if it is raining in the biome. It points to this line here: https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/powermodule/energy/AdvancedSolarGenerator.java#L78

I'm working on a pure Java port (no Scala) of MPS for 1.7.10 to aid with porting to 1.10.2 and above. I'll probably include the fix for this in there.

**Comment by lehjr** [comment]
This should no longer be an issue in 1.10.2 due to code changes. However if it returns we can revisit.
