### ISSUE TITLE
[Question] Is the new code released anywhere at the moment?

### ISSUE THREAD

**Issue by sscards55** [MachineMuse/MachineMusePowersuits#762]

**Comment by lehjr** [comment]
You're gonna need to be a lot more specific than that.

**Comment by lehjr** [comment]
If you're asking whether or not the code from the last commit that I uploaded last night is in any released build, then the answer is no. It needs more testing before I upload it due to changes in the code. As far as when that will happen, probably not until forge gradle connection issues are resolved.

**Comment by sscards55** [comment]
Sorry I found it.
I meant that if the new 1.10.2 code was available anywhere. I didn't see there was a separate branch.
The curse links go the experimental branch rather than the 1.10.2 branch.
