### ISSUE TITLE
[1.10.2] Mekanism Conflict issue

### ISSUE THREAD

**Issue by MJRLegends** [MachineMuse/MachineMusePowersuits#820]
See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/140

Modular Powersuits Version: 1.2.125
Forge Version: 12.18.3.2422
Mekanism Version: 9.2.4.103

**Comment by lehjr** [comment]
Another one? I'll check it out this weekend. With these well documented bug reports the bugs aren't usually hard to find. Much easier than the typical "it doesn't work" reports.

**Comment by MJRLegends** [comment]
@lehjr Haha yeah another one, Let me know if you need any more information or me to test something :P

**Comment by lehjr** [comment]
Verified already so I have all the info I need, thanks.

**Comment by lunarbunny** [comment]
Just want to point out that this also happens when you install either of the solar generator modules as well.
Also it doesn't only happen to Atomic Disassemblers it seems to affect the Configurator I had in my inventory too. It doesn't affect energy cubes.

Forge and Mek version is same as OP's but I'm on v1.2.124 MPS.

**Comment by lehjr** [comment]
@SwiftingDuster 1.2.124 had issues with Mekanism power which is why 1.2.125 was released

**Comment by lehjr** [comment]
I think I might have a fix ready, but it will need more testing before I release it.

**Comment by MJRLegends** [comment]
Sounds good

**Comment by lehjr** [comment]
Fixed version is uploaded and should be visible soon.

**Comment by MJRLegends** [comment]
Thank you, amazing work :P
