### ISSUE TITLE
Chisel mod conflicts 1.7.10

### ISSUE THREAD

**Issue by StefanH-AT** [MachineMuse/MachineMusePowersuits#919]
After installing Chisel mod, the Power Fist mines Stone extremely slow (Speed of the bare hand).
A cobblestone item will still be dropped however. All other ores and blocks work as intended.

Other Chisel specific rock variants are also affected. 

I do have the Diamond Drill, Pickaxe Upgrade and even the Chisel upgrade.

**Comment by lehjr** [comment]
this is why I hate even trying to support 1.7.10, especially while supporting 1 current version and working on 1 future version.

**Comment by eyeonus** [comment]
Then don't. How old is 1.7.10 now?

**Comment by eyeonus** [comment]
Any people experiencing an issue, the following are REQUIRED to get any help:

--------
#### Issue Submission Form
ALL fields required!
1. Java version:
2. Minecraft Forge version:
3. Detailed description of the issue:
a. What the issue is:
b. What happens when the issue occurs:
c. What steps need to be taken to reproduce the issue:
d. Anything else relevant to the issue not already covered (for example, if it only occurs on existing saves, but doesn't show up when starting a new game):
4. Mod list (including versions, provided by crash report if game crashed):
a. Smallest sub-list that still produces issue, if any exclusion testing was done:
5. Log files (Link to pastebin, gist, or other hosting site preferred, file attachment okay, do NOT paste directly):
a. Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
b. Crash report (if issue caused game to crash):
c. Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
d. Server crash report (if issue caused server to crash):
6. Anything else relevant (such as links to issue reports for other mods when issue is due to mod compatibility issues, for example):

--------

**Comment by lehjr** [comment]
For the longest time, the only reason I tried to maintain the 1.7.10 version is the continued popularity, like 9 out of every 10 downloads being for the 1.7.10 version. That appears to no longer be the case.

**Comment by eyeonus** [comment]
I will say, I do remember back when I was still playing on 1.7.10, the fist did have trouble with non-vanilla blocks. I think I might've even been the person to raise the issue after the jump 1.8? I know this issue has been raised before, and I know you've already fixed it in current versions....

**Comment by lehjr** [comment]
And the gist of it was and is that the block breaking mechanic is horrible, starting in vanilla and radiating outward into mods. There's no standardized way of doing it. Add to that, the way that this mod works makes it even more complex and more prone to failure. The reality is you can either have more customization, or you can have more reliability, but you can't have both.
