### ISSUE TITLE
Any people experiencing an issue, the following are REQUIRED to get any help:

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#923]
Any people experiencing an issue, the following are REQUIRED to get any help:

--------
#### Issue Submission Form
ALL fields required!
1. Java version:
2. Minecraft Forge version:
3. Detailed description of the issue:
a. What the issue is:
b. What happens when the issue occurs:
c. What steps need to be taken to reproduce the issue:
d. Anything else relevant to the issue not already covered (for example, if it only occurs on existing saves, but doesn't show up when starting a new game):
4. Mod list (including versions, provided by crash report if game crashed):
a. Smallest sub-list that still produces issue, if any exclusion testing was done:
5. Log files (Link to pastebin, gist, or other hosting site preferred, file attachment okay, do NOT paste directly):
a. Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
b. Crash report (if issue caused game to crash):
c. Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
d. Server crash report (if issue caused server to crash):
6. Anything else relevant (such as links to issue reports for other mods when issue is due to mod compatibility issues, for example):

--------

**Comment by EzerArch** [comment]
Suggestion to the devs: create an ISSUE_TEMPLATE.md in the repo.

**Comment by eyeonus** [comment]
*dev

lehjr is the only one working on this. I've just been trying to help mitigate the annoyance.

Also, the people that posted the issues which prompted this almost definitely would never have seen such a template, whereas this is something they at least _might_ see.

**Comment by lehjr** [comment]
Unfortunately, it's gotten to the point where the total sum of information given is little more than "I have a problem and I want you to fix it". I wish I was kidding.

The reality is that there is very little incentive to keep going. I do it mainly because I've already been doing it for 3 years now. I do get some level of enjoyment out of the work itself. I have to, because at about $10 a month on a good month, I'm certainly not getting rich.

**Comment by eyeonus** [comment]
Well, I for one am damned happy that you are, because this is literally my favourite Minecraft Mod, and I would be super sad if it stopped being one I can put in my modlist.

**Comment by lehjr** [comment]
At the moment, I'm distro hopping while I wait for Forge and breaking changes to settle down. Currently I'm on Pop!_OS, and I do like that it is very fast. However, Gnome. 

Edit: 
Found an extension or 2 that makes Gnome actually usable. Will probably just stay with Pop!_OS until I manage to break something.

**Comment by EzerArch** [comment]
> Also, the people that posted the issues which prompted this almost definitely would never have seen such a template, whereas this is something they at least might see.

I'm afraid that my message was too short. Let me explain a bit further: You can create an `ISSUE_TEMPLATE.md` at repo root so that a form like you wrote is auto-generated when one clicks on "New issue" button.

Example on Galacticraft repo: see [`ISSUE_TEMPLATE.md`](https://github.com/micdoodle8/Galacticraft/blob/master/ISSUE_TEMPLATE) and now [try to create an issue there](https://github.com/micdoodle8/Galacticraft/issues/new). :)

EDIT: If I'm not wrong, you can also pin 2 issues per repo.

> Unfortunately, it's gotten to the point where the total sum of information given is little more than "I have a problem and I want you to fix it". I wish I was kidding.

Oh those people, I feel ya.. You should've seen how MachineMuse handled "my car's broken, fix it" people on Minecraft Forums and complained she had to keep spoonfeeding them. Once she got a warning from a moderator because she had been too trollish to people  :smile: ... but hey! I _wouldn't_ recommend following the same path... no no no. ;x _(but they deserved)_

>  I have to, because at about $10 a month on a good month, I'm certainly not getting rich.

Is it on Patreon?

> Well, I for one am damned happy that you are, because this is literally my favourite Minecraft Mod, and I would be super sad if it stopped being one I can put in my modlist.

Same here. MPS is was mod that got me hooked on the modded Minecraft. I used to think MPS was one of the few actual mods back then because it actually added something new to the game other than "look at these new ores, retextured tools and food with a pretentious name" mod.

**Comment by lehjr** [comment]
$10 a month is from Curse Authors rewards in the form of points that can be redeemed for Amazon gift cards, when and if they feel like restocking them, or for PayPal gift cards when they feel like processing them.

Pateron for me is kind of one of those areas where I'm just not sure where I want to venture. In the past I was open to it, but one of the things that turned me off from it was how a certain mod's development was handled after one of its developers retired from the mod and the remaining dev was stringing people along for YEARS saying he was actively working on updating the mod, and then finally the truth came out that he never got past setting up the development environment, despite hundreds of dollars a month in donations. I just don't want to end up being that guy. On the other hand, $10 a month doesn't even cover the cost of electricity used in working on the mod. So I don't know. 

In terms of trolling users that cannot file bug reports properly, I'm not above that, nor am I above trolling myself if I feel it's deserved.

**Comment by lehjr** [comment]
Btw, the issue with creating a template is that I cannot even change the default branch which is why the landing page is still stuck on 1.10.2

**Comment by eyeonus** [comment]
I created the template and issued a pull request, but someone with write access to the repo needs to accept the PR for the template to be a thing.
